name: RpgParty
main: com.vartala.soulofw0lf.rpgparty.RpgParty
version: 1.2.1
author: RC2K7.soulofw0lf
description: Party Plugin Designed By RC2K7 and finished by soulofw0lf

commands:
  party:
    description: Party Command Central
    usage: /<command> <invite|kick|accept|deny|leave|chat>
    aliases: [p,pc,rparty]
  pcc:
    description: Party Chat
    usage: /<command> TEXT
    
permissions:
  party.invite:
    description: Allows party invitations.
    default: op
  party.summon:
    description: Allows Party Leader To Teleport Members
    default: op